Update .circleci/config.yml
Co-authored-by: Sean Rose <1994030+sean-rose@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,10 +40,10 @@ jobs:
           name: Execute linting
           command: |
             npm install -g @looker/look-at-me-sideways@3
-            if lams --reporting=no;
-              then echo "No linting errors found.";
-              else echo "Linting errors found."; exit 1;
-            fi;
+            if lams --reporting=no
+              then echo "No linting errors found."
+              else echo "Linting errors found."; exit 1
+            fi
   push-lookml-for-validation:
     executor: docker/machine
     steps:
